# Generated by Django 5.2.6 on 2025-09-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bandwidth', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_cap', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('service_type', models.CharField(choices=[('PPPoE', 'PPPoE'), ('Hotspot', 'Hotspot')], max_length=10)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('next_billing_date', models.DateField()),
                ('mikrotik_profile', models.CharField(default='default', max_length=50)),
                ('is_synced', models.BooleanField(default=False)),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.serviceplan')),
            ],
        ),
    ]
