# Generated by Django 5.2.6 on 2025-09-28 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='connection_status',
            field=models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected'), ('Expired', 'Expired')], default='Disconnected', max_length=12),
        ),
        migrations.AddField(
            model_name='client',
            name='last_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='mpesa_number',
            field=models.CharField(default='0706315742', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='duration_hours',
            field=models.IntegerField(default=720),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_number', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.serviceplan')),
            ],
        ),
    ]
