# Generated by Django 5.2.6 on 2025-09-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ipv4_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='physical_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='router_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
