# Generated by Django 5.2.6 on 2025-09-29 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_userprofile_installation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('network', models.GenericIPAddressField(protocol='IPv4')),
                ('subnet_mask', models.PositiveIntegerField(default=24)),
                ('gateway', models.GenericIPAddressField(protocol='IPv4')),
                ('start_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('end_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('dns_servers', models.CharField(default='8.8.8.8,8.8.4.4', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='installation_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ipv4_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_seen_online',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='router_port',
        ),
        migrations.AddField(
            model_name='client',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ipv4_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_seen_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='physical_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='router_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ip_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.ippool'),
        ),
    ]
